In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [5]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
df.drop(columns = "Cabin", axis = True, inplace = True)
df.fillna(df["Age"].mean(), inplace = True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,Q

In [7]:
df.dropna(inplace = True)

In [8]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [9]:
df.drop(["PassengerId","Name", "Ticket", "Embarked"], axis = 1, inplace = True)

In [10]:
df

     Survived  Pclass     Sex        Age  SibSp  Parch     Fare
0           0       3    male  22.000000      1      0   7.2500
1           1       1  female  38.000000      1      0  71.2833
2           1       3  female  26.000000      0      0   7.9250
3           1       1  female  35.000000      1      0  53.1000
4           0       3    male  35.000000      0      0   8.0500
..        ...     ...     ...        ...    ...    ...      ...
886         0       2    male  27.000000      0      0  13.0000
887         1       1  female  19.000000      0      0  30.0000
888         0       3  female  29.699118      1      2  23.4500
889         1       1    male  26.000000      0      0  30.0000
890         0       3    male  32.000000      0      0   7.7500

[891 rows x 7 columns]

In [11]:
df["Family"] = df["SibSp"] + df["Parch"]

In [12]:
df.drop(["SibSp","Parch"], axis = 1, inplace = True)

In [13]:
df

     Survived  Pclass     Sex        Age     Fare  Family
0           0       3    male  22.000000   7.2500       1
1           1       1  female  38.000000  71.2833       1
2           1       3  female  26.000000   7.9250       0
3           1       1  female  35.000000  53.1000       1
4           0       3    male  35.000000   8.0500       0
..        ...     ...     ...        ...      ...     ...
886         0       2    male  27.000000  13.0000       0
887         1       1  female  19.000000  30.0000       0
888         0       3  female  29.699118  23.4500       3
889         1       1    male  26.000000  30.0000       0
890         0       3    male  32.000000   7.7500       0

[891 rows x 6 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Sex"] = le.fit_transform(df["Sex"])
df

     Survived  Pclass  Sex        Age     Fare  Family
0           0       3    1  22.000000   7.2500       1
1           1       1    0  38.000000  71.2833       1
2           1       3    0  26.000000   7.9250       0
3           1       1    0  35.000000  53.1000       1
4           0       3    1  35.000000   8.0500       0
..        ...     ...  ...        ...      ...     ...
886         0       2    1  27.000000  13.0000       0
887         1       1    0  19.000000  30.0000       0
888         0       3    0  29.699118  23.4500       3
889         1       1    1  26.000000  30.0000       0
890         0       3    1  32.000000   7.7500       0

[891 rows x 6 columns]

In [15]:
x = df.iloc[:,1:]
x

     Pclass  Sex        Age     Fare  Family
0         3    1  22.000000   7.2500       1
1         1    0  38.000000  71.2833       1
2         3    0  26.000000   7.9250       0
3         1    0  35.000000  53.1000       1
4         3    1  35.000000   8.0500       0
..      ...  ...        ...      ...     ...
886       2    1  27.000000  13.0000       0
887       1    0  19.000000  30.0000       0
888       3    0  29.699118  23.4500       3
889       1    1  26.000000  30.0000       0
890       3    1  32.000000   7.7500       0

[891 rows x 5 columns]

In [16]:
y = df.iloc[:,0]
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size = 0.3, random_state = 42)

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report

In [19]:
lr = LogisticRegression()
knn = KNeighborsClassifier()
dt = DecisionTreeClassifier()
svm = SVC()

In [20]:
def mymodel(model):
    model.fit(xtrain, ytrain)
    ypred = model.predict(xtest)
    print(classification_report(ytest, ypred))
    return model

In [21]:
mymodel(lr)

              precision    recall  f1-score   support

           0       0.81      0.88      0.84       157
           1       0.80      0.70      0.75       111

    accuracy                           0.81       268
   macro avg       0.81      0.79      0.80       268
weighted avg       0.81      0.81      0.80       268

LogisticRegression()

In [22]:
mymodel(knn)

              precision    recall  f1-score   support

           0       0.72      0.81      0.76       157
           1       0.67      0.56      0.61       111

    accuracy                           0.71       268
   macro avg       0.70      0.68      0.69       268
weighted avg       0.70      0.71      0.70       268

KNeighborsClassifier()

In [23]:
mymodel(dt)

              precision    recall  f1-score   support

           0       0.78      0.82      0.80       157
           1       0.73      0.67      0.69       111

    accuracy                           0.76       268
   macro avg       0.75      0.74      0.75       268
weighted avg       0.76      0.76      0.76       268

DecisionTreeClassifier()

In [24]:
mymodel(svm)

              precision    recall  f1-score   support

           0       0.64      0.94      0.76       157
           1       0.74      0.26      0.39       111

    accuracy                           0.66       268
   macro avg       0.69      0.60      0.57       268
weighted avg       0.68      0.66      0.61       268

SVC()

In [25]:
svm = SVC(kernel = "linear")
mymodel(svm)

              precision    recall  f1-score   support

           0       0.80      0.85      0.83       157
           1       0.77      0.70      0.74       111

    accuracy                           0.79       268
   macro avg       0.79      0.78      0.78       268
weighted avg       0.79      0.79      0.79       268

SVC(kernel='linear')

# Grid Search

In [29]:
from sklearn.model_selection import GridSearchCV
param_grid = {"C":[1,10], "gamma": [1,10]}
gs = GridSearchCV(svm, param_grid, verbose = 4)
gs.fit(xtrain,ytrain)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV 1/5] END ......................C=1, gamma=1;, score=0.736 total time=  12.3s
[CV 2/5] END ......................C=1, gamma=1;, score=0.880 total time=   7.1s
[CV 3/5] END ......................C=1, gamma=1;, score=0.712 total time=  22.5s
[CV 4/5] END ......................C=1, gamma=1;, score=0.782 total time=   9.3s
[CV 5/5] END ......................C=1, gamma=1;, score=0.815 total time=  10.7s
[CV 1/5] END .....................C=1, gamma=10;, score=0.736 total time=  12.4s
[CV 2/5] END .....................C=1, gamma=10;, score=0.880 total time=   7.1s
[CV 3/5] END .....................C=1, gamma=10;, score=0.712 total time=  22.7s
[CV 4/5] END .....................C=1, gamma=10;, score=0.782 total time=   8.9s
[CV 5/5] END .....................C=1, gamma=10;, score=0.815 total time=   9.8s
[CV 1/5] END .....................C=10, gamma=1;, score=0.736 total time=  37.0s
[CV 2/5] END .....................C=10, gamma=1;, score=0.880 total time=  25.3s
[CV 3/5] END .....................C=10, gamma=1;, score=0.712 total time=  57.0s
[CV 4/5] END .....................C=10, gamma=1;, score=0.782 total time=  26.6s
[CV 5/5] END .....................C=10, gamma=1;, score=0.815 total time=  33.8s
[CV 1/5] END ....................C=10, gamma=10;, score=0.736 total time=  37.5s
[CV 2/5] END ....................C=10, gamma=10;, score=0.880 total time=  24.9s
[CV 3/5] END ....................C=10, gamma=10;, score=0.712 total time=  57.6s
[CV 4/5] END ....................C=10, gamma=10;, score=0.782 total time=  27.2s
[CV 5/5] END ....................C=10, gamma=10;, score=0.815 total time=  33.8s

GridSearchCV(estimator=SVC(kernel='linear'),
             param_grid={'C': [1, 10], 'gamma': [1, 10]}, verbose=4)

In [30]:
gs.best_params_

{'C': 1, 'gamma': 1}

In [31]:
svm = SVC(kernel = "linear", C = 1, gamma = 1)
mymodel(svm)

              precision    recall  f1-score   support

           0       0.80      0.85      0.83       157
           1       0.77      0.70      0.74       111

    accuracy                           0.79       268
   macro avg       0.79      0.78      0.78       268
weighted avg       0.79      0.79      0.79       268

SVC(C=1, gamma=1, kernel='linear')